# Generated by Django 4.0.6 on 2023-02-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(max_length=50, null=True, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='company_name'),
        ),
    ]
