# Generated by Django 4.0.6 on 2023-02-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_company_company_id_alter_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
    ]
