# Generated by Django 4.0.6 on 2023-02-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
