# Generated by Django 4.0.6 on 2023-03-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_company_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='hotel_name')),
                ('hotel_location', models.CharField(blank=True, max_length=155, null=True, verbose_name='hotel_location')),
                ('hotel_website', models.CharField(blank=True, max_length=500, null=True, verbose_name='website')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Food',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='supplier',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='product',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='customer',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.hotel'),
            preserve_default=False,
        ),
    ]
